---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: pacman-ch
  namespace: pacman
spec:
  type: GitHub
  pathname: https://github.com/ocp-tigers/rhacm-demo.git
  #pathname: https://github.com/avaleror/rhacm-demo.git
  secretRef:
    name: acm-app-secret
